object Versions {
    const val kotlin = "1.3.61"
    const val material = "1.2.0-alpha05"
    const val navigation = "2.2.2"
    const val retrofit = "2.6.1"
    const val logging_interceptor = "4.1.1"
    const val room = "2.2.5"
    const val glide = "4.11.0"
    const val glideToVectorYou = "v2.0.0"
    const val dagger = "2.27"
    const val dagger_android = "2.25.3"
    const val rxjava = "3.0.3"
    const val rxandroid = "3.0.0"
    const val rxkotlin = "3.0.0"
    const val APP_COMPAT = "1.1.0"
    const val CORE_KTX = "1.2.0"
    const val CONSTRAINT = "1.1.3"
    const val LIFECYCLE = "2.2.0"
    const val JUNIT = "4.12"
    const val ANDROID_JUNIT = "1.1.1"
    const val ANDROID_ESPRESSO = "3.2.0"
    const val RECYCLER = "1.1.0"
    const val SWIPE_REFRESH = "1.0.0"
    const val DIAGRAMS = "v3.1.0"
}